name: gis_toolbox
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # -- Core Python & CUDA --
  - python=3.8
  - cudatoolkit=11.2
  
  # -- RAPIDS & GPU libs --
  - cudf=22.06.00
  - cuspatial=22.06.00
  - rmm=22.06.00
  - numba=0.56.4
  - llvmlite=0.39.1
  - cupy=10.6.0

  # -- Geo/Spatial libs --
  - geopandas=0.9.0
  - rasterio=1.2.10
  - shapely=1.8.0
  - fiona=1.8.20
  - pygeos=0.10.2
  - pyogrio=0.2.0
  - pyproj=3.2.1
  - rtree=1.3.0

  # -- Data & analytics --
  - pandas=1.4.4
  - scipy=1.10.1
  - scikit-learn=1.3.2
  - numpy=1.23.5
  - pyarrow=7.0.0
  - fastavro=1.9.5
  - numexpr=2.8.4

  # -- I/O & file formats --
  - gdal=3.3.3
  - libgdal=3.3.3
  - parquet-cpp=1.5.1
  - orc=1.7.5

  # -- Visualization --
  - matplotlib=3.7.1
  - folium=0.18.0

  # -- Common Python deps --
  - requests=2.32.3
  - tqdm=4.67.1
  - click=8.1.7
  - setuptools=75.3.0
  - pip=24.3.1
  - wheel=0.45.1
  - python-dateutil=2.9.0
  - typing_extensions=4.12.2
  - packaging=24.2
  - importlib-metadata=8.5.0
  - zipp=3.21.0

  # -- The large pinned block that might be needed or not --
  #    Many of these are sub-dependencies pinned in your original file.
  #    If you do not strictly need them pinned, consider removing them.
  - affine=2.4.0
  - attrs=24.2.0
  - blosc=1.21.5
  - boost-cpp=1.74.0
  - bottleneck=1.3.7
  - branca=0.7.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.31
  - cachetools=5.5.0
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - cfitsio=3.470
  - charset-normalizer=3.4.0
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - contourpy=1.1.1
  - curl=8.1.1
  - cycler=0.12.1
  - dlpack=0.5
  - fastrlock=0.8.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2024.10.0
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - grpc-cpp=1.46.3
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=68.2
  - idna=3.10
  - importlib-resources=6.4.5
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.15
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.19.4
  - lcms2=2.12
  - lerc=4.0.0
  - libabseil=20211102.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcudf=22.06.00
  - libcurl=8.1.1
  - libcuspatial=22.06.00
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.1
  - libgomp=14.2.0
  - libgoogle-cloud=1.40.2
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libpq=13.5
  - libprotobuf=3.20.3
  - librmm=22.06.01
  - librttopo=1.1.0
  - libspatialindex=2.0.0
  - libspatialite=5.0.1
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.9.12
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - mapclassify=2.5.0
  - markupsafe=2.1.5
  - munch=4.0.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.1
  - nspr=4.36
  - nss=3.89.1
  - nvtx=0.2.10
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=24.2
  - pcre=8.45
  - pcre2=10.40
  - pixman=0.44.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - poppler=21.09.0
  - poppler-data=0.4.12
  - postgresql=13.5
  - proj=8.1.1
  - protobuf=3.20.3
  - pycparser=2.22
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python_abi=3.8
  - pytz=2024.2
  - re2=2022.04.01
  - readline=8.2
  - s2n=1.0.10
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - spdlog=1.10.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - thrust=1.16.0
  - tiledb=2.3.4
  - tk=8.6.13
  - tzcode=2024b
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.2.3
  - xerces-c=3.2.3
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xyzservices=2024.9.0
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6

